---
- name: decrypt private SSL key
  command: >-
    openssl rsa
    -in {{ ssl_dest_encrypted_key_path }}
    -out {{ ssl_dest_key_path }}
    -passin pass: {{ ssl_key_password }}

- name: set private SSL key permissions
  file:
    path: "{{ ssl_dest_key_path }}"
    owner: "{{ ssl_user }}"
    group: "{{ ssl_group }}"
    mode: 0640
