---
- debug: 
    msg: "{{ openstax_ssl_role }}"

- include_tasks: create_dirs.yml
  tags: create-dirs
- include_tasks: boto.yml
  tags: boto
- include_tasks: pull_ssl_certs_from_s3.yml
  tags: pull-certs

