---
# FIXME: 
- name: pull certificate from s3
  become: yes
  aws_s3:
    mode: get
    bucket: "{{ openstax_ssl_role.s3_bucket }}"
    object: "{{ openstax_ssl_role.s3_cert_object_main }}"
    dest: "/etc/ssl/certs/{{ openstax_ssl_role.ssl_cert_file_name }}_head"
    aws_access_key: "{{ openstax_ssl_role.s3_access_key_id }}"
    aws_secret_key: "{{ openstax_ssl_role.s3_secret_access_key }}"
  tags: ssl

- name: pull certificate bundle from s3
  become: yes
  aws_s3:
    mode: get
    bucket: "{{ openstax_ssl_role.s3_bucket }}"
    object: "{{ openstax_ssl_role.s3_cert_object_main }}"
    dest: "/etc/ssl/certs/{{ openstax_ssl_role.ssl_cert_file_name }}_inter"
    aws_access_key: "{{ openstax_ssl_role.s3_access_key_id }}"
    aws_secret_key: "{{ openstax_ssl_role.s3_secret_access_key }}"
  
- name: concatenate the certs
  become: yes
  shell: "cat /etc/ssl/certs/{{ openstax_ssl_role.ssl_cert_file_name }}_head /etc/ssl/certs/{{ openstax_ssl_role.ssl_cert_file_name }}_inter > /etc/ssl/certs/{{ openstax_ssl_role.ssl_cert_file_name }}"

- name: pull key from s3
  become: yes
  aws_s3: 
    mode: get
    bucket: "{{ openstax_ssl_role.s3_bucket }}"
    object: "{{ openstax_ssl_role.s3_key_object }}"
    dest: "/etc/ssl/private/{{ openstax_ssl_role.s3_key_name }}"
    aws_access_key: "{{ openstax_ssl_role.s3_access_key_id }}"
    aws_secret_key: "{{ openstax_ssl_role.s3_secret_access_key }}"

- name: set certificate permissions
  become: yes
  file: 
    path: "/etc/ssl/certs/{{ openstax_ssl_role.ssl_cert_file_name }}"
    mode: 0644
    group: ssl-cert
  notify: restart nginx

- name: set key permissions
  become: yes
  file:
    path: "/etc/ssl/private/{{ openstax_ssl_role.s3_key_name }}"
    mode: 0640
    group: ssl-cert

